### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by MoonWolf125**

### CODE REVIEW

**Comment by alunduil** [comment]
Was this repo following git flow or did I just make that up?

**Comment by MoonWolf125** [comment]
Yeah, I'm easing into it with everyone. Not everyone has the time to sit down with me and work through an example or two. The other thing is that I'm writing all of the content and it's up to the last minute that I need a PR done. In essence, things are hectic. I'm hoping that after May I can sit down and really iron out the branching strategy with the new officers and members.

**Comment by alunduil** [comment]
@MoonWolf125 that sounds good.  Remember you can use branch protections to enforce this as you get more and more on board with following a process.  In such a public repository it might even be good to set those restrictions on administrators (you can always turn it off for a quick hotfix).

**Comment by MoonWolf125** [comment]
@alunduil Dually noted. I already have master with a simple 2 acceptance revision protection, but I'm still in the process of teaching others about that. At some point the master protection will be a bit more restrictive and dev will most likely have a loose protection. Thanks!

**Pull request merged**
